### ISSUE TITLE
Video not exists

### ISSUE THREAD

**Issue by trappedinspacetime** [ScarletsFiction/LittleYoutube-PHP#1]
First of all, thank you for coding `LittleYoutube-PHP`.

I noticed that it doesn't show `mp4` links anymore. I checked out the error log:

    Video not exist
    #0 /src/LittleYoutube.php(147): LittleYoutube\LittleYoutubeInfo->onError('Video not exist')
    #1 /src/LittleYoutube.php(88): LittleYoutube\Video->processDetails()
    #2 /src/LittleYoutube.php(34): LittleYoutube\Video->init('https://www.you...')
    #3 /src/LittleYoutube.php(970): LittleYoutube\LittleYoutubeInfo->__construct('https://www.you...', Array)
    #4 /example/base.php(30): LittleYoutube\LittleYoutube::video('https://www.you...', Array)
    #5 {main}

**Comment by StefansArya** [comment]
Hi!
Thank you for reporting, I don't noticed because I was working on other project.
I will looking into it.

**Comment by StefansArya** [comment]
I have updated the script, please try again and tell me if the problem still exist :)

**Comment by trappedinspacetime** [comment]
Thank you for responding. I just tried it, unfortunately links in the `Video` tab redirects to `localhost` instead of actual links.

**Comment by StefansArya** [comment]
Oh sorry, its my bad because not recheck with another video that doesn't need signature deciphering 😅

**Comment by trappedinspacetime** [comment]
Thank you for the fix. It works well.
