### ISSUE TITLE
Issue In direct link for often videos 

### ISSUE THREAD

**Issue by Hamza7Oqbah** [ScarletsFiction/LittleYoutube-PHP#2]
when i enter a link often videos youtube its success get info title,viewed,image and Qualites .etc But when i clicked on any Buttons download it's do not work, i see direct link like "https://littleyoutube.herokuapp.com/&title=AWARD+WINNING+Best+Short+Video+-+Share...+Care...+Joy...++-+By+Naik+Foundation" - like this link video https://www.youtube.com/watch?v=HkuKHwetV6Q and https://www.youtube.com/watch?v=5ikDI6PFTUU and more , please fix this problem

**Comment by StefansArya** [comment]
Hi!
looks like I was missed something and it has been fixed on latest commit.
Btw there are still open issue about for video problem #1, if the problem still exist please comment on there instead of opening similar issue.

**Comment by Hamza7Oqbah** [comment]
Thank you many thanks for the most wonderful project and your reaction and launch new updates first Powell .. Thank you really
